sudo: required

dist: bionic

language: python

python:

  - "3.8"

install: 

   - pip install xml2rfc

script:

  - xml2rfc --legacy draft-bosh-dots-quick-blocks.xml > draft-bosh-dots-quick-blocks.txt


 
